"""empty message

Revision ID: f60c2b75de63
Revises: 
Create Date: 2017-10-22 07:56:57.722452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60c2b75de63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('facebook_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('image_link', sa.String(length=100), nullable=False),
    sa.Column('language', sa.Enum('english', 'spanish', name='languageenum'), nullable=False),
    sa.Column('country_of_origin', sa.String(length=3), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('bio', sa.String(length=90), nullable=False),
    sa.Column('interest', sa.String(length=40), nullable=False),
    sa.Column('role', sa.Enum('mentee', 'mentor', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('facebook_id')
    )
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor', sa.Integer(), nullable=False),
    sa.Column('mentee', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mentee'], ['user.facebook_id'], ),
    sa.ForeignKeyConstraint(['mentor'], ['user.facebook_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sent_by', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['sent_by'], ['user.facebook_id'], ),
    sa.PrimaryKeyConstraint('conversation_id', 'sent_by')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('conversation')
    op.drop_table('user')
    # ### end Alembic commands ###
